### ISSUE TITLE
upgrade pexpect past 3.2

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocflib#11]
in setup.py:
```python
        # pexpect 3.3 (currently the latest) breaks with multiprocessing/celery
        # https://github.com/pexpect/pexpect/issues/86
        'pexpect<3.2.999',
```

looks like we're up to pexpect 4.0.1, so we can probably unpin that, just need some small amount of testing

**Comment by matthew-mcallister** [comment]
pexpect 4.0.1 can't be installed in wheezy since it uses syntax from python 3.3+, e.g. unicode string literals. This can wait until we upgrade the remaining two holdouts to jessie.

**Comment by chriskuehl** [comment]
should be finally done in https://github.com/ocf/ocflib/commit/e90e524f08808b796a8e5db2a05f5814c30dd37e
