### ISSUE TITLE
similarity_heuristic is bad

### ISSUE THREAD

**Issue by bjb568** [ocf/ocflib#136]
The code smells and it has a ton of false positives and false negatives. I couldn't even describe to you what the function does without specifying the names of the _multiple_ algorithms involved as well as the order and limits with which it processes match attempts. It would better off returning `random.choice([0, 3])`. This isn't to say that there's a better algorithm that can be used or that the code ought to be cleaned up, though those are probably both true statements, but the fundamental problem with requiring a similar username and real name is that not only is that similarity subjective, but nobody even knows what it means. That makes this not just a code smell, but a UX smell.

- If you want to be real draconian about having usernames be real names, generate the usernames programmatically and don't let the user change it without contacting humans (to deal with the edge case that your programatic solution makes their name sound offensive or something).
- Probably the best thing to do is remove the check and allow some freedom.

**Comment by gpl** [comment]
lol

**Comment by kkuehler** [comment]
thanks

**Comment by keur** [comment]
@bjb568 have you gotten the chance to work on this at all?

**Comment by bjb568** [comment]
I don't think a good programatic solution exists.

**Comment by dkess** [comment]
It's fine if you want to make it more strict-- it'll just lead to more manual approvals over IRC.

**Comment by bjb568** [comment]
I don't want to make it more strict. 💯

**Comment by itskevinwang** [comment]
aww my username got rejected :(

**Comment by daradib** [comment]
As the author of this special snowflake of a function, I want to apologize for all its defects and limitations. I'm rather surprised it hasn't been replaced in over 7 years. That said, I'd like to think it did a relatively decent job at minimizing the effort of a real name policy. ML would create an even more draconian code smell wrapped in an opaque box.

Without a real name checker, groups creating individual accounts, requests for account name changes, or offensive/hateful/trademark names might become more common, but I'm sure you've all judged the tradeoff to be worth it. Perhaps individual web hosting (where the username is public) is less applicable today.

**Comment by bjb568** [comment]
TODO: add text to tell the user that their OCF account is tied to their calnet account.
