### ISSUE TITLE
Add kanboard support

### ISSUE THREAD

**Issue by dkess** [ocf/ocflib#162]
See [ocflib.infra.discourse](https://github.com/ocf/ocflib/blob/master/ocflib/infra/discourse.py) for inspiration on how to do this. I believe users can make personal Kanboard tokens for this (for testing purposes), and ircbot can use the global admin token.

This is necessary for https://github.com/ocf/ircbot/issues/106

**Comment by willtunnels** [comment]
Looks like the Kanboard API uses JSON-RPC 2. We have a couple options:
(1) add the official kanboard python client as a dependency (might be overkill unless we plan on adding more kanboard functionality)
(2) do an ad hoc request with the right format
(3) add a generic JSON-RPC library as a dependency (probably not)

**Comment by dkess** [comment]
Their documentation has examples that use `curl`, so I assume it won't be too hard for us to make ad-hoc requests with the right format (using the `requests` library).

**Comment by cg505** [comment]
I believe this should have been closed.
