### ISSUE TITLE
Replace references to Hearst Gym with MLK

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocflib#7]
See also https://github.com/ocf/ocfweb/issues/81.

**Comment by jvperrin** [comment]
Is this done now? I'm assuming it is, but I'm not sure if there are any lingering references anywhere that haven't fully been removed yet.

**Comment by hexecute** [comment]
These aren't too important but...

https://github.com/ocf/puppet/blob/94fdb84f8886ad29024a5cfe51be8c232318c220/modules/ocf_mail/files/site_ocf/postfix/main.cf
https://github.com/ocf/puppet/blob/7c0e6150886cf63767be5e61e1d2a050b8f7be94/modules/ocf_mirrors/files/vsftpd.conf

Also: https://www.ocf.berkeley.edu/~ckuehl/

**Comment by chriskuehl** [comment]
yea, so seems the ocflib portion is done
I tried to fix the puppet ones but couldn't come up with anything as catchy as "Hearst Gym Grotto".

also need to change the welcome text on blackhole which has the same line
https://www.ocf.berkeley.edu/docs/staff/backend/switch/

**Comment by chriskuehl** [comment]
Migrated to https://github.com/ocf/puppet/issues/33
