### ISSUE TITLE
Fix `ocflib.lab.stats.list_desktops(public_only=True)`

### ISSUE THREAD

**Issue by kpengboy** [ocf/ocflib#85]
The LDAP queries are outdated since we moved the relevant setting to hiera.

@jvperrin PuppetDB can handle this, right?

**Comment by matthew-mcallister** [comment]
Something like PuppetDB would be ideal, but I wouldn't hold my breath waiting on it. In the meantime, I think it would be OK to hard-code at least eruption and possibly the front desk computer in ocflib.
